In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('check_data_1.csv')

In [3]:
df.head()

Date  Temperature (°C)  Humidity (%)  Wind Speed (km/h)  \
0  01-01-2025         26.236204     49.891265          36.499916   
1  02-01-2025         43.521429     46.632968           9.225600   
2  03-01-2025         36.959818     34.092313          17.331985   
3  04-01-2025         32.959755     68.581334          33.164032   
4  05-01-2025         19.680559     58.129933          24.104467   

   Pressure (hPa)  Disaster Likelihood  
0     1013.814457                    0  
1      995.929245                    0  
2     1046.449852                    0  
3      971.897845                    0  
4     1008.785642                    0

In [4]:
df['Disaster Likelihood'].value_counts()

Disaster Likelihood
0    9865
1     251
Name: count, dtype: int64

In [5]:
df.describe()

Temperature (°C)  Humidity (%)  Wind Speed (km/h)  Pressure (hPa)  \
count      10116.000000  10116.000000       10116.000000    10116.000000   
mean          29.830344     60.363362          25.088698      999.705570   
std            8.637763     23.158943          15.128429       31.056447   
min           10.761991     20.012620           0.002406      200.300420   
25%           22.389866     40.295199          12.769194      974.685725   
50%           29.784014     60.465755          25.144088      999.983831   
75%           37.210614     80.527686          37.243135     1024.681775   
max           49.855307     99.993986         370.602346     1200.586411   

       Disaster Likelihood  
count         10116.000000  
mean              0.024812  
std               0.155560  
min               0.000000  
25%               0.000000  
50%               0.000000  
75%               0.000000  
max               1.000000

In [6]:
df.isna().sum()

Date                   0
Temperature (°C)       0
Humidity (%)           0
Wind Speed (km/h)      0
Pressure (hPa)         0
Disaster Likelihood    0
dtype: int64

In [7]:
from sklearn.utils import resample

In [8]:
df_minority=df[df['Disaster Likelihood']==1]
df_majority=df[df['Disaster Likelihood']==0]

In [9]:
df_minority.shape

(251, 6)

In [10]:
df_majority.shape

(9865, 6)

In [11]:
# Upsampling
df_minority_upsample = resample(df_minority, replace=True,
                       n_samples=len(df_majority),
                               random_state=42)

In [12]:
df_minority_upsample.shape

(9865, 6)

In [13]:
df_upsampled = pd.concat([df_majority,df_minority_upsample]).reset_index(drop=True)

In [14]:
df_upsampled.shape

(19730, 6)

In [15]:
df_upsampled['Disaster Likelihood'].value_counts()

Disaster Likelihood
0    9865
1    9865
Name: count, dtype: int64

In [16]:
# model training
X = df_upsampled.drop(['Disaster Likelihood','Date'], axis=1)
y = df_upsampled['Disaster Likelihood']

In [17]:
X

Temperature (°C)  Humidity (%)  Wind Speed (km/h)  Pressure (hPa)
0             26.236204     49.891265          36.499916     1013.814457
1             43.521429     46.632968           9.225600      995.929245
2             36.959818     34.092313          17.331985     1046.449852
3             32.959755     68.581334          33.164032      971.897845
4             19.680559     58.129933          24.104467     1008.785642
...                 ...           ...                ...             ...
19725         42.305884     92.758169          39.601070      984.082202
19726         35.728132     81.012205          43.533224      971.241844
19727         42.739533     91.066770          36.119962      957.587779
19728         36.378640     37.076921          44.944288     1018.365428
19729         43.842499     81.203455          34.345499      986.249598

[19730 rows x 4 columns]

In [18]:
y

0        0
1        0
2        0
3        0
4        0
        ..
19725    1
19726    1
19727    1
19728    1
19729    1
Name: Disaster Likelihood, Length: 19730, dtype: int64

In [19]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [20]:
X_train.shape,y_train.shape

((13811, 4), (13811,))

In [21]:
y_train.value_counts()

Disaster Likelihood
1    6931
0    6880
Name: count, dtype: int64

In [22]:
# scaler the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [23]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled

array([[ 0.64168342,  0.96701248, -0.16535502, -0.0513975 ],
       [ 0.56896676,  1.21183029,  0.62343683,  0.20845827],
       [-0.22443241, -1.45475501, -0.76153208,  1.27179874],
       ...,
       [-1.13478992, -0.70186731, -0.441936  ,  0.18040534],
       [-1.24227406, -1.79332731, -0.51164673, -0.02904755],
       [ 0.55570396,  0.85319942,  0.26786989, -0.00814422]])

In [25]:
# model training
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(verbose=3)

In [26]:
model.fit(X_train_scaled,y_train)

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100


[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.6s


building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82

RandomForestClassifier(verbose=3)

In [27]:
y_pred = model.predict(X_test_scaled)

[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.0s


In [28]:
y_pred

array([1, 0, 1, ..., 0, 1, 1])

In [29]:
# calculate score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [30]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9964521033958439
[[2964   21]
 [   0 2934]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      2985
           1       0.99      1.00      1.00      2934

    accuracy                           1.00      5919
   macro avg       1.00      1.00      1.00      5919
weighted avg       1.00      1.00      1.00      5919



In [31]:
y_pred_train = model.predict(X_train_scaled)

[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.0s


In [32]:
print(accuracy_score(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))

0.9958728549706756
[[6823   57]
 [   0 6931]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6880
           1       0.99      1.00      1.00      6931

    accuracy                           1.00     13811
   macro avg       1.00      1.00      1.00     13811
weighted avg       1.00      1.00      1.00     13811



In [33]:
import pickle
with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [35]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)