In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('check_data_1.csv')

In [3]:
df.head()

Date  Temperature (°C)  Humidity (%)  Wind Speed (km/h)  \
0  01-01-2025         26.236204     49.891265          36.499916   
1  02-01-2025         43.521429     46.632968           9.225600   
2  03-01-2025         36.959818     34.092313          17.331985   
3  04-01-2025         32.959755     68.581334          33.164032   
4  05-01-2025         19.680559     58.129933          24.104467   

   Pressure (hPa)  Disaster Likelihood  
0     1013.814457                    0  
1      995.929245                    0  
2     1046.449852                    0  
3      971.897845                    0  
4     1008.785642                    0

In [4]:
df['Disaster Likelihood'].value_counts()

Disaster Likelihood
0    9843
1     157
Name: count, dtype: int64

In [5]:
df.describe()

Temperature (°C)  Humidity (%)  Wind Speed (km/h)  Pressure (hPa)  \
count      10000.000000  10000.000000       10000.000000    10000.000000   
mean          29.824787     60.362390          25.002520      999.871338   
std            8.628904     23.143564          14.338688       28.899459   
min           15.000349     20.012620           0.002406      950.000554   
25%           22.389866     40.315664          12.687396      974.685725   
50%           29.775859     60.471742          25.103405     1000.003024   
75%           37.200190     80.518338          37.233693     1024.711626   
max           44.991530     99.993986          49.995049     1049.978937   

       Disaster Likelihood  
count         10000.000000  
mean              0.015700  
std               0.124318  
min               0.000000  
25%               0.000000  
50%               0.000000  
75%               0.000000  
max               1.000000

In [6]:
df.isna().sum()

Date                   0
Temperature (°C)       0
Humidity (%)           0
Wind Speed (km/h)      0
Pressure (hPa)         0
Disaster Likelihood    0
dtype: int64

In [7]:
from sklearn.utils import resample

In [8]:
df_minority=df[df['Disaster Likelihood']==1]
df_majority=df[df['Disaster Likelihood']==0]

In [9]:
df_minority.shape

(157, 6)

In [10]:
df_majority.shape

(9843, 6)

In [11]:
# Upsampling
df_minority_upsample = resample(df_minority, replace=True,
                       n_samples=len(df_majority),
                               random_state=42)

In [12]:
df_minority_upsample.shape

(9843, 6)

In [13]:
df_upsampled = pd.concat([df_majority,df_minority_upsample]).reset_index(drop=True)

In [14]:
df_upsampled.shape

(19686, 6)

In [15]:
df_upsampled['Disaster Likelihood'].value_counts()

Disaster Likelihood
0    9843
1    9843
Name: count, dtype: int64

In [16]:
# model training
X = df_upsampled.drop(['Disaster Likelihood','Date'], axis=1)
y = df_upsampled['Disaster Likelihood']

In [17]:
X

Temperature (°C)  Humidity (%)  Wind Speed (km/h)  Pressure (hPa)
0             26.236204     49.891265          36.499916     1013.814457
1             43.521429     46.632968           9.225600      995.929245
2             36.959818     34.092313          17.331985     1046.449852
3             32.959755     68.581334          33.164032      971.897845
4             19.680559     58.129933          24.104467     1008.785642
...                 ...           ...                ...             ...
19681         37.518443     89.465917          46.000789      970.920748
19682         40.900009     99.946810          45.244831      975.314908
19683         42.305884     92.758169          39.601070      984.082202
19684         41.819691     85.604749          40.127178      967.544869
19685         40.341275     89.966361          32.171053      961.753111

[19686 rows x 4 columns]

In [18]:
y

0        0
1        0
2        0
3        0
4        0
        ..
19681    1
19682    1
19683    1
19684    1
19685    1
Name: Disaster Likelihood, Length: 19686, dtype: int64

In [19]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [20]:
X_train.shape,y_train.shape

((13780, 4), (13780,))

In [21]:
y_train.value_counts()

Disaster Likelihood
1    6901
0    6879
Name: count, dtype: int64

In [22]:
# scaler the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [23]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled

array([[ 0.17757413,  0.91201893, -2.30025904, -1.31944708],
       [ 0.53238216,  0.96994936,  0.3782977 , -0.08870804],
       [-1.96431235, -2.08161449, -0.73067375, -0.0523984 ],
       ...,
       [ 0.54888587, -0.29530171, -1.54432869, -0.84984723],
       [-1.84442626, -1.36427708, -1.1972891 , -0.351714  ],
       [ 0.98273521,  0.57779387,  0.69202158, -0.09751275]])

In [25]:
# model training
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(verbose=3)

In [26]:
model.fit(X_train_scaled,y_train)

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
b

[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.3s


building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88

RandomForestClassifier(verbose=3)

In [27]:
y_pred = model.predict(X_test_scaled)

[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.0s


In [28]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [29]:
# calculate score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [30]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[2964    0]
 [   0 2942]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2964
           1       1.00      1.00      1.00      2942

    accuracy                           1.00      5906
   macro avg       1.00      1.00      1.00      5906
weighted avg       1.00      1.00      1.00      5906



In [31]:
y_pred_train = model.predict(X_train_scaled)

[Parallel(n_jobs=1)]: Done  31 tasks      | elapsed:    0.0s


In [32]:
print(accuracy_score(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))

1.0
[[6879    0]
 [   0 6901]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6879
           1       1.00      1.00      1.00      6901

    accuracy                           1.00     13780
   macro avg       1.00      1.00      1.00     13780
weighted avg       1.00      1.00      1.00     13780



In [33]:
import pickle
with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [34]:
# convert into dl
import tensorflow as tf

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [36]:
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,961 (35.00 KB)

 Trainable params: 8,961 (35.00 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [41]:
Early_stoping = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=5)

In [42]:
history = model.fit(
    X_train_scaled,y_train,validation_data=(X_test_scaled,y_test),epochs=50,batch_size=32,verbose=1,
    callbacks=[Early_stoping]
)

Epoch 1/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9683 - loss: 0.1711 - val_accuracy: 0.9897 - val_loss: 0.0380
Epoch 2/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9899 - loss: 0.0388 - val_accuracy: 0.9929 - val_loss: 0.0240
Epoch 3/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9928 - loss: 0.0243 - val_accuracy: 0.9964 - val_loss: 0.0179
Epoch 4/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9936 - loss: 0.0215 - val_accuracy: 0.9959 - val_loss: 0.0131
Epoch 5/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9950 - loss: 0.0180 - val_accuracy: 0.9970 - val_loss: 0.0086
Epoch 6/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9959 - loss: 0.0133 - val_accuracy: 0.9983 - val_loss: 0.0068
Epoch 7/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9971 - loss: 0.0100 - val_accuracy: 0.9988 - val_loss: 0.0067
Epoch 8/50
431/431 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9978 - loss: 0.0073 - val_accuracy: 0.

In [43]:
# Convert to TFLite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()



Saved artifact at '/tmp/tmp2lj0t9zm'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 4), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  139111557781232: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139111514547728: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139112893806048: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139111512560512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139111512562272: TensorSpec(shape=(), dtype=tf.resource, name=None)
  139111512563152: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [44]:
# Save the TFLite model
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

In [45]:
# data for scaling
scaler.mean_

array([ 34.83898524,  75.15512242,  31.91727892, 986.96119244])

In [46]:
scaler.scale_

array([ 8.21632595, 22.59535275, 13.0861531 , 26.59615109])