In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [35]:
df = pd.read_csv('Flood_data.csv')

In [36]:
df.head()

temp  max_temp  wind_speed  cloudcover  precip  humidity  class
0  29.90     37.00       23.00       58.60  146.00     83.86      1
1  93.04     82.41       63.44      102.42  192.07    129.30      1
2  87.13     98.82       72.29      122.12  191.80    142.25      1
3  92.12     72.39       73.84       96.50  196.53    150.42      1
4  92.64     76.03       67.13       92.61  191.76    126.61      1

In [37]:
df.isnull().sum()

temp          0
max_temp      0
wind_speed    0
cloudcover    0
precip        0
humidity      0
class         0
dtype: int64

In [38]:
df['class'].value_counts()

class
1    3000
0    2040
Name: count, dtype: int64

In [39]:
df.head()

temp  max_temp  wind_speed  cloudcover  precip  humidity  class
0  29.90     37.00       23.00       58.60  146.00     83.86      1
1  93.04     82.41       63.44      102.42  192.07    129.30      1
2  87.13     98.82       72.29      122.12  191.80    142.25      1
3  92.12     72.39       73.84       96.50  196.53    150.42      1
4  92.64     76.03       67.13       92.61  191.76    126.61      1

In [40]:
# depedent and indepedent 
X = df.drop('class', axis=1)

y = df['class']

In [41]:
X.shape

(5040, 6)

In [42]:
# train and test split data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
X_train.shape

(3528, 6)

In [44]:
X_test.shape

(1512, 6)

In [45]:
# scaling the feature
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

In [47]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [48]:
# model training
import tensorflow as tf

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [50]:
model = Sequential()
model.add(Dense(64, input_shape=(X_train_scaled.shape[1],), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


d:\PU_Code_hackathon\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [51]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,073 (12.00 KB)

 Trainable params: 3,073 (12.00 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [53]:
Early_stop = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=5)

In [54]:
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, 
                    validation_data=(X_test_scaled, y_test), 
                    callbacks=[Early_stop])

Epoch 1/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8325 - loss: 0.4478 - val_accuracy: 0.9597 - val_loss: 0.1095
Epoch 2/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9590 - loss: 0.1052 - val_accuracy: 0.9749 - val_loss: 0.0741
Epoch 3/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9684 - loss: 0.0741 - val_accuracy: 0.9795 - val_loss: 0.0559
Epoch 4/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9764 - loss: 0.0629 - val_accuracy: 0.9815 - val_loss: 0.0476
Epoch 5/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9786 - loss: 0.0489 - val_accuracy: 0.9841 - val_loss: 0.0451
Epoch 6/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9775 - loss: 0.0577 - val_accuracy: 0.9841 - val_loss: 0.0423
Epoch 7/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9797 - loss: 0.0470 - val_accuracy: 0.9841 - val_loss: 0.0415
Epoch 8/100
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9868 - loss: 0.0335 - val_accu

In [55]:
# Convert to TFLite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\YASHSA~1\AppData\Local\Temp\tmpl6utcuq9\assets


INFO:tensorflow:Assets written to: C:\Users\YASHSA~1\AppData\Local\Temp\tmpl6utcuq9\assets


Saved artifact at 'C:\Users\YASHSA~1\AppData\Local\Temp\tmpl6utcuq9'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 6), dtype=tf.float32, name='keras_tensor_11')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  1398765761744: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765751376: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765762704: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765751568: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765761936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765764432: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398765763664: TensorSpec(shape=(), dtype=tf.resource, name=None)
  1398807200976: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [56]:
# Save the TFLite model
with open('flood_model.tflite', 'wb') as f:
    f.write(tflite_model)

In [57]:
scaler.mean_

array([ 74.97693311,  82.27992347,  65.80187358,  99.08653345,
       245.98496315, 118.38806689])

In [58]:
scaler.scale_

array([ 14.73319989,  15.04007007,  17.82595228,  31.99059663,
       242.66751962,  24.44959974])

In [59]:
# prediction and score
y_pred  = model.predict(X_test_scaled)

48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [60]:
y_pred.round()

array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [61]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred.round()))
print(confusion_matrix(y_test, y_pred.round()))


              precision    recall  f1-score   support

           0       0.98      0.97      0.98       596
           1       0.98      0.99      0.99       916

    accuracy                           0.98      1512
   macro avg       0.98      0.98      0.98      1512
weighted avg       0.98      0.98      0.98      1512

[[581  15]
 [ 11 905]]
